apiVersion: apps/v1
kind: Deployment
metadata:
  name: orenotorero-api
spec:
  selector:
    matchLabels:
      app: orenotorero-api
  template:
    metadata:
      labels:
        app: orenotorero-api
    spec:
      containers:
        - name: orenotorero-api
          image: orenotorero-api
          imagePullPolicy: Never
          env:
            - name: IP
              value: $IP
          ports:
            - containerPort: 3000
          command:
            - sh
            - -c
            - ./binary/orenotorero

---
apiVersion: v1
kind: Service
metadata:
  name: orenotorero-api
spec:
  selector:
    app: orenotorero-api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort
