apiVersion: apps/v1
kind: Deployment
metadata:
  name: orenotorero-app
spec:
  selector:
    matchLabels:
      app: orenotorero-app
  template:
    metadata:
      labels:
        app: orenotorero-app
    spec:
      containers:
      - name: orenotorero-app
        image: orenotorero-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: orenotorero-app
spec:
  selector:
    app: orenotorero-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  type: NodePort