apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
data:
  password: cm9vdA==
  database: b3Jlbm90b3Jlcm8=

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: orenotorero-db
  labels:
    app: orenotorero-db
spec:
  selector:
    matchLabels:
      app: orenotorero-db
      tier: orenotorero-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orenotorero-db
        tier: orenotorero-db
    spec:
      containers:
        - image: mysql:5.7
          name: orenotorero-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                  secretKeyRef:
                    name: dbsecret
                    key: database
          ports:
            - containerPort: 3306
              name: orenotorero-db

---

apiVersion: v1
kind: Service
metadata:
  name: orenotorero-db
  labels:
    app: orenotorero-db
spec:
  ports:
    - port: 30002
      targetPort: 3306
  selector:
    app: orenotorero-db
    tier: orenotorero-db
  type: ClusterIP
